#!/usr/bin/env python3
"""
OpenCode Markdown to PDF Converter
使用 Python + weasyprint 将 markdown 文档转换为 PDF
"""

import os
import sys
import subprocess
from pathlib import Path


def check_dependencies():
    """检查并安装必要的依赖"""
    print("🔍 检查依赖...")

    # 检查 weasyprint
    try:
        import weasyprint

        print("✓ weasyprint 已安装")
    except ImportError:
        print("📦 正在安装 weasyprint...")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "weasyprint"],
            capture_output=True,
            check=True,
        )
        print("✓ weasyprint 安装完成")

    # 检查 markdown2
    try:
        import markdown2

        print("✓ markdown2 已安装")
    except ImportError:
        print("📦 正在安装 markdown2...")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "markdown2"],
            capture_output=True,
            check=True,
        )
        print("✓ markdown2 安装完成")


def convert_to_pdf(md_path: str, pdf_path: str) -> bool:
    """使用 weasyprint 将 markdown 转换为 PDF"""
    print(f"📄 正在转换: {md_path}")
    print(f"📤 目标 PDF: {pdf_path}")

    try:
        # 使用 weasyprint 命令
        cmd = [
            sys.executable,
            "-m",
            "weasyprint",
            "--no-merged-pdf",
            "--no-wrapped-pdf",
            "--output-format=pdf14",
            "--encoding=utf-8",
            "--page-size=A4",
            "--margin-top=72",
            "--margin-bottom=72",
            "--margin-left=72",
            "--margin-right=72",
            "--footer-spacing=1",
            "--footer=Draft - Generated by OpenCode Architecture Analysis",
            "--display-settings",
            md_path,
            "-o",
            pdf_path,
        ]

        result = subprocess.run(
            cmd, capture_output=True, text=True, check=True, encoding="utf-8"
        )

        if result.returncode == 0:
            print("✅ PDF 生成成功！")
            print(f"📂 PDF 已保存到: {pdf_path}")
            print(f"📏 文件大小: {os.path.getsize(pdf_path) / 1024:.2f} KB")
            return True
        else:
            print(f"❌ 转换失败，错误码: {result.returncode}")
            print(f"错误输出: {result.stderr}")
            return False

    except FileNotFoundError as e:
        print(f"❌ 文件不存在: {md_path}")
        return False
    except Exception as e:
        print(f"❌ 转换过程出错: {e}")
        return False


def main():
    """主函数"""
    if len(sys.argv) < 2:
        print("使用方法:")
        print("  python convert_to_pdf.py <markdown文件> <输出PDF文件>")
        print("\n推荐的安装命令:")
        print("  pip install weasyprint markdown2")
        sys.exit(1)

    md_path = sys.argv[1]
    pdf_path = sys.argv[2] if len(sys.argv) > 2 else md_path.replace(".md", ".pdf")

    # 检查文件是否存在
    if not os.path.exists(md_path):
        print(f"❌ 错误: markdown 文件不存在: {md_path}")
        sys.exit(1)

    # 检查依赖
    print("\n🔍 检查依赖...")
    check_dependencies()
    print()

    # 执行转换
    print(f"\n🚀 开始转换...")
    success = convert_to_pdf(md_path, pdf_path)

    if success:
        print("\n✅ 转换完成！")
    else:
        print("\n❌ 转换失败，请查看错误信息")
        sys.exit(1)


if __name__ == "__main__":
    main()
